ALTER TABLE MSG_TPRL_ORDER 
 ADD (
  ORDERNO VARCHAR2 (250 CHAR)
 )
/
ALTER TABLE MSG_TPRL_ORDER_HIST 
 ADD (
  ORDERNO VARCHAR2 (250 CHAR)
 )
/
ALTER TABLE MSG_TPRL_OUTRIGHT 
 ADD (
  ORDERNO VARCHAR2 (250 CHAR)
 )
/
ALTER TABLE MSG_TPRL_OUTRIGHT_HIST 
 ADD (
  ORDERNO VARCHAR2 (250 CHAR)
 )
/
ALTER TABLE MSG_TPRL_REPO 
 ADD (
  ORDERNO VARCHAR2 (250 CHAR)
 )
/
ALTER TABLE MSG_TPRL_REPO_HIST 
 ADD (
  ORDERNO VARCHAR2 (250 CHAR)
 )
/
ALTER TABLE MSG_TPRL_HNX_CONFIRM 
 ADD (
  ORDERNO VARCHAR2 (250 CHAR)
 )
/
ALTER TABLE MSG_TPRL_HNX_CONFIRM_HIST 
 ADD (
  ORDERNO VARCHAR2 (250 CHAR)
 )
/