//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNXTPRLGate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HNXTPRLGate.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string lblAdmin {
            get {
                return ResourceManager.GetString("lblAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Error.
        /// </summary>
        public static string lblApplicationError {
            get {
                return ResourceManager.GetString("lblApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string lblControl {
            get {
                return ResourceManager.GetString("lblControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel.
        /// </summary>
        public static string lblControlPanel {
            get {
                return ResourceManager.GetString("lblControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable kafka.
        /// </summary>
        public static string lblEnableKafka {
            get {
                return ResourceManager.GetString("lblEnableKafka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HỆ THỐNG GIÁM SÁT GATE TRÁI PHIẾU RIÊNG LẺ.
        /// </summary>
        public static string lblHeThongGateTPRL {
            get {
                return ResourceManager.GetString("lblHeThongGateTPRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HNX Connection Infor.
        /// </summary>
        public static string lblHNXConnectionInfor {
            get {
                return ResourceManager.GetString("lblHNXConnectionInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string lblIP {
            get {
                return ResourceManager.GetString("lblIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAFKA Connection Infor.
        /// </summary>
        public static string lblKafkaConnectionInfor {
            get {
                return ResourceManager.GetString("lblKafkaConnectionInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last processed sequence.
        /// </summary>
        public static string lblLastProcessedSequence {
            get {
                return ResourceManager.GetString("lblLastProcessedSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống.
        /// </summary>
        public static string lblLoiHeThong {
            get {
                return ResourceManager.GetString("lblLoiHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string lblNA {
            get {
                return ResourceManager.GetString("lblNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number message send.
        /// </summary>
        public static string lblNumberMessageSend {
            get {
                return ResourceManager.GetString("lblNumberMessageSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên giao dịch.
        /// </summary>
        public static string lblPhienGiaoDich {
            get {
                return ResourceManager.GetString("lblPhienGiaoDich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string lblPort {
            get {
                return ResourceManager.GetString("lblPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string lblRequest {
            get {
                return ResourceManager.GetString("lblRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string lblSequence {
            get {
                return ResourceManager.GetString("lblSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string lblSubmit {
            get {
                return ResourceManager.GetString("lblSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string lblSymbol {
            get {
                return ResourceManager.GetString("lblSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string lblThongBao {
            get {
                return ResourceManager.GetString("lblThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Order Execution.
        /// </summary>
        public static string lblTopicOrderExection {
            get {
                return ResourceManager.GetString("lblTopicOrderExection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Order Status.
        /// </summary>
        public static string lblTopicOrderStatus {
            get {
                return ResourceManager.GetString("lblTopicOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Trading Information.
        /// </summary>
        public static string lblTopicTradingInfomartion {
            get {
                return ResourceManager.GetString("lblTopicTradingInfomartion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading session request.
        /// </summary>
        public static string lblTradingSessionRequest {
            get {
                return ResourceManager.GetString("lblTradingSessionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái giao dịch.
        /// </summary>
        public static string lblTrangThaiGiaoDich {
            get {
                return ResourceManager.GetString("lblTrangThaiGiaoDich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu gửi thông tin phiên giao dịch.
        /// </summary>
        public static string lblYeuCauGuiThongTinPhienGiaoDich {
            get {
                return ResourceManager.GetString("lblYeuCauGuiThongTinPhienGiaoDich", resourceCulture);
            }
        }
    }
}
